name: Build and Publish Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare tags
      id: prep
      run: |
        REPO_NAME="${GITHUB_REPOSITORY##*/}"
        BRANCH_NAME="$(echo ${GITHUB_REF#refs/heads/} | sed 's/[^a-zA-Z0-9._-]/-/g')"
        SHORT_SHA="$(echo ${GITHUB_SHA::7})"
        echo "::set-output name=repo_name::$REPO_NAME"
        echo "::set-output name=branch_name::$BRANCH_NAME"
        echo "::set-output name=short_sha::$SHORT_SHA"

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ steps.prep.outputs.repo_name }}:${{ steps.prep.outputs.branch_name }}
          ghcr.io/${{ github.repository_owner }}/${{ steps.prep.outputs.repo_name }}:${{ steps.prep.outputs.short_sha }}
          ghcr.io/${{ github.repository_owner }}/${{ steps.prep.outputs.repo_name }}:latest